name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run Go Vet
        run: go vet ./...
      - name: Check Format
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "Go files are not formatted:"
            gofmt -l .
            exit 1
          fi
